/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.NetworkMessage', null, global);
goog.exportSymbol('proto.NetworkMessage.StarBroadcast', null, global);
goog.exportSymbol('proto.NetworkMessage.StarConnection', null, global);
goog.exportSymbol('proto.NetworkMessage.StarUnicast', null, global);
goog.exportSymbol('proto.RouterMessage', null, global);
goog.exportSymbol('proto.RouterMessage.Notification', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.NetworkMessage.oneofGroups_);
};
goog.inherits(proto.NetworkMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.NetworkMessage.displayName = 'proto.NetworkMessage';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.NetworkMessage.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.NetworkMessage.VariantCase = {
  VARIANT_NOT_SET: 0,
  STAR_CONNECTION: 2,
  STAR_UNICAST: 3,
  STAR_BROADCAST: 4
};

/**
 * @return {proto.NetworkMessage.VariantCase}
 */
proto.NetworkMessage.prototype.getVariantCase = function() {
  return /** @type {proto.NetworkMessage.VariantCase} */(jspb.Message.computeOneofCase(this, proto.NetworkMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.NetworkMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    networkId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    starConnection: (f = msg.getStarConnection()) && proto.NetworkMessage.StarConnection.toObject(includeInstance, f),
    starUnicast: (f = msg.getStarUnicast()) && proto.NetworkMessage.StarUnicast.toObject(includeInstance, f),
    starBroadcast: (f = msg.getStarBroadcast()) && proto.NetworkMessage.StarBroadcast.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkMessage}
 */
proto.NetworkMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkMessage;
  return proto.NetworkMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkMessage}
 */
proto.NetworkMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetworkId(value);
      break;
    case 2:
      var value = new proto.NetworkMessage.StarConnection;
      reader.readMessage(value,proto.NetworkMessage.StarConnection.deserializeBinaryFromReader);
      msg.setStarConnection(value);
      break;
    case 3:
      var value = new proto.NetworkMessage.StarUnicast;
      reader.readMessage(value,proto.NetworkMessage.StarUnicast.deserializeBinaryFromReader);
      msg.setStarUnicast(value);
      break;
    case 4:
      var value = new proto.NetworkMessage.StarBroadcast;
      reader.readMessage(value,proto.NetworkMessage.StarBroadcast.deserializeBinaryFromReader);
      msg.setStarBroadcast(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.NetworkMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNetworkId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStarConnection();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.NetworkMessage.StarConnection.serializeBinaryToWriter
    );
  }
  f = message.getStarUnicast();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.NetworkMessage.StarUnicast.serializeBinaryToWriter
    );
  }
  f = message.getStarBroadcast();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.NetworkMessage.StarBroadcast.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkMessage.StarConnection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.NetworkMessage.StarConnection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.NetworkMessage.StarConnection.displayName = 'proto.NetworkMessage.StarConnection';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkMessage.StarConnection.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkMessage.StarConnection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkMessage.StarConnection} msg The msg instance to transform.
 * @return {!Object}
 */
proto.NetworkMessage.StarConnection.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkMessage.StarConnection}
 */
proto.NetworkMessage.StarConnection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkMessage.StarConnection;
  return proto.NetworkMessage.StarConnection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkMessage.StarConnection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkMessage.StarConnection}
 */
proto.NetworkMessage.StarConnection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkMessage.StarConnection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkMessage.StarConnection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkMessage.StarConnection} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.NetworkMessage.StarConnection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkMessage.StarUnicast = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.NetworkMessage.StarUnicast, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.NetworkMessage.StarUnicast.displayName = 'proto.NetworkMessage.StarUnicast';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkMessage.StarUnicast.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkMessage.StarUnicast.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkMessage.StarUnicast} msg The msg instance to transform.
 * @return {!Object}
 */
proto.NetworkMessage.StarUnicast.toObject = function(includeInstance, msg) {
  var f, obj = {
    senderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    recipientId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkMessage.StarUnicast}
 */
proto.NetworkMessage.StarUnicast.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkMessage.StarUnicast;
  return proto.NetworkMessage.StarUnicast.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkMessage.StarUnicast} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkMessage.StarUnicast}
 */
proto.NetworkMessage.StarUnicast.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRecipientId(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkMessage.StarUnicast.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkMessage.StarUnicast.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkMessage.StarUnicast} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.NetworkMessage.StarUnicast.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSenderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRecipientId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
};


/**
 * optional string sender_id = 1;
 * @return {string}
 */
proto.NetworkMessage.StarUnicast.prototype.getSenderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.NetworkMessage.StarUnicast.prototype.setSenderId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string recipient_id = 2;
 * @return {string}
 */
proto.NetworkMessage.StarUnicast.prototype.getRecipientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.NetworkMessage.StarUnicast.prototype.setRecipientId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bytes body = 3;
 * @return {!(string|Uint8Array)}
 */
proto.NetworkMessage.StarUnicast.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes body = 3;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.NetworkMessage.StarUnicast.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.NetworkMessage.StarUnicast.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/** @param {!(string|Uint8Array)} value */
proto.NetworkMessage.StarUnicast.prototype.setBody = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.NetworkMessage.StarBroadcast = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.NetworkMessage.StarBroadcast, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.NetworkMessage.StarBroadcast.displayName = 'proto.NetworkMessage.StarBroadcast';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.NetworkMessage.StarBroadcast.prototype.toObject = function(opt_includeInstance) {
  return proto.NetworkMessage.StarBroadcast.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.NetworkMessage.StarBroadcast} msg The msg instance to transform.
 * @return {!Object}
 */
proto.NetworkMessage.StarBroadcast.toObject = function(includeInstance, msg) {
  var f, obj = {
    senderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.NetworkMessage.StarBroadcast}
 */
proto.NetworkMessage.StarBroadcast.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.NetworkMessage.StarBroadcast;
  return proto.NetworkMessage.StarBroadcast.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.NetworkMessage.StarBroadcast} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.NetworkMessage.StarBroadcast}
 */
proto.NetworkMessage.StarBroadcast.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderId(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.NetworkMessage.StarBroadcast.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.NetworkMessage.StarBroadcast.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.NetworkMessage.StarBroadcast} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.NetworkMessage.StarBroadcast.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSenderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional string sender_id = 1;
 * @return {string}
 */
proto.NetworkMessage.StarBroadcast.prototype.getSenderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.NetworkMessage.StarBroadcast.prototype.setSenderId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional bytes body = 2;
 * @return {!(string|Uint8Array)}
 */
proto.NetworkMessage.StarBroadcast.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes body = 2;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.NetworkMessage.StarBroadcast.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.NetworkMessage.StarBroadcast.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/** @param {!(string|Uint8Array)} value */
proto.NetworkMessage.StarBroadcast.prototype.setBody = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string network_id = 1;
 * @return {string}
 */
proto.NetworkMessage.prototype.getNetworkId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.NetworkMessage.prototype.setNetworkId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional StarConnection star_connection = 2;
 * @return {?proto.NetworkMessage.StarConnection}
 */
proto.NetworkMessage.prototype.getStarConnection = function() {
  return /** @type{?proto.NetworkMessage.StarConnection} */ (
    jspb.Message.getWrapperField(this, proto.NetworkMessage.StarConnection, 2));
};


/** @param {?proto.NetworkMessage.StarConnection|undefined} value */
proto.NetworkMessage.prototype.setStarConnection = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.NetworkMessage.oneofGroups_[0], value);
};


proto.NetworkMessage.prototype.clearStarConnection = function() {
  this.setStarConnection(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.NetworkMessage.prototype.hasStarConnection = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional StarUnicast star_unicast = 3;
 * @return {?proto.NetworkMessage.StarUnicast}
 */
proto.NetworkMessage.prototype.getStarUnicast = function() {
  return /** @type{?proto.NetworkMessage.StarUnicast} */ (
    jspb.Message.getWrapperField(this, proto.NetworkMessage.StarUnicast, 3));
};


/** @param {?proto.NetworkMessage.StarUnicast|undefined} value */
proto.NetworkMessage.prototype.setStarUnicast = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.NetworkMessage.oneofGroups_[0], value);
};


proto.NetworkMessage.prototype.clearStarUnicast = function() {
  this.setStarUnicast(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.NetworkMessage.prototype.hasStarUnicast = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional StarBroadcast star_broadcast = 4;
 * @return {?proto.NetworkMessage.StarBroadcast}
 */
proto.NetworkMessage.prototype.getStarBroadcast = function() {
  return /** @type{?proto.NetworkMessage.StarBroadcast} */ (
    jspb.Message.getWrapperField(this, proto.NetworkMessage.StarBroadcast, 4));
};


/** @param {?proto.NetworkMessage.StarBroadcast|undefined} value */
proto.NetworkMessage.prototype.setStarBroadcast = function(value) {
  jspb.Message.setOneofWrapperField(this, 4, proto.NetworkMessage.oneofGroups_[0], value);
};


proto.NetworkMessage.prototype.clearStarBroadcast = function() {
  this.setStarBroadcast(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.NetworkMessage.prototype.hasStarBroadcast = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.RouterMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.RouterMessage.oneofGroups_);
};
goog.inherits(proto.RouterMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.RouterMessage.displayName = 'proto.RouterMessage';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.RouterMessage.oneofGroups_ = [[2]];

/**
 * @enum {number}
 */
proto.RouterMessage.VariantCase = {
  VARIANT_NOT_SET: 0,
  NOTIFICATION: 2
};

/**
 * @return {proto.RouterMessage.VariantCase}
 */
proto.RouterMessage.prototype.getVariantCase = function() {
  return /** @type {proto.RouterMessage.VariantCase} */(jspb.Message.computeOneofCase(this, proto.RouterMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.RouterMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.RouterMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.RouterMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.RouterMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    channelId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    notification: (f = msg.getNotification()) && proto.RouterMessage.Notification.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.RouterMessage}
 */
proto.RouterMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.RouterMessage;
  return proto.RouterMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.RouterMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.RouterMessage}
 */
proto.RouterMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelId(value);
      break;
    case 2:
      var value = new proto.RouterMessage.Notification;
      reader.readMessage(value,proto.RouterMessage.Notification.deserializeBinaryFromReader);
      msg.setNotification(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.RouterMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.RouterMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.RouterMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.RouterMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChannelId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNotification();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.RouterMessage.Notification.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.RouterMessage.Notification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.RouterMessage.Notification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.RouterMessage.Notification.displayName = 'proto.RouterMessage.Notification';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.RouterMessage.Notification.prototype.toObject = function(opt_includeInstance) {
  return proto.RouterMessage.Notification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.RouterMessage.Notification} msg The msg instance to transform.
 * @return {!Object}
 */
proto.RouterMessage.Notification.toObject = function(includeInstance, msg) {
  var f, obj = {
    body: msg.getBody_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.RouterMessage.Notification}
 */
proto.RouterMessage.Notification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.RouterMessage.Notification;
  return proto.RouterMessage.Notification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.RouterMessage.Notification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.RouterMessage.Notification}
 */
proto.RouterMessage.Notification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.RouterMessage.Notification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.RouterMessage.Notification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.RouterMessage.Notification} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.RouterMessage.Notification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBody_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes body = 1;
 * @return {!(string|Uint8Array)}
 */
proto.RouterMessage.Notification.prototype.getBody = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes body = 1;
 * This is a type-conversion wrapper around `getBody()`
 * @return {string}
 */
proto.RouterMessage.Notification.prototype.getBody_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBody()));
};


/**
 * optional bytes body = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBody()`
 * @return {!Uint8Array}
 */
proto.RouterMessage.Notification.prototype.getBody_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBody()));
};


/** @param {!(string|Uint8Array)} value */
proto.RouterMessage.Notification.prototype.setBody = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string channel_id = 1;
 * @return {string}
 */
proto.RouterMessage.prototype.getChannelId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.RouterMessage.prototype.setChannelId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional Notification notification = 2;
 * @return {?proto.RouterMessage.Notification}
 */
proto.RouterMessage.prototype.getNotification = function() {
  return /** @type{?proto.RouterMessage.Notification} */ (
    jspb.Message.getWrapperField(this, proto.RouterMessage.Notification, 2));
};


/** @param {?proto.RouterMessage.Notification|undefined} value */
proto.RouterMessage.prototype.setNotification = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.RouterMessage.oneofGroups_[0], value);
};


proto.RouterMessage.prototype.clearNotification = function() {
  this.setNotification(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.RouterMessage.prototype.hasNotification = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
